# EasyChannels
# Chat channels, without the fuss
#
# Setup instructions: https://github.com/Dinty1/EasyChannels/wiki/Configuration
#
# If you have any issues, please join this Discord server: https://dinty1.github.io/plugins-discord or open an issue on GitHub (https://github.com/Dinty1/EasyChannels)
#
# You MUST restart your server to apply channel-related config changes. Otherwise, you may use /easychannels reloadconfig.
#
# Please don't touch this
config-version: ${project.version}
#
# Whether players with the easychannels.adminalerts permission should be notified of available updates when they log in
notify-admins-of-updates: true
#
# Whether to modify the global chat format (keep this disabled if you modify chat with another chat plugin)
modify-global-chat: false
#
# The global chat format
# Available placeholders:
# - %username% - The player's username
# - %displayname% - The player's displayname
# - %message% - The message
# - %prefix% - The player's prefix
# - %suffix% - The player's suffix
# - Any PAPI placeholders
global-format: "<%username%> %message%"
#
# Messages
# If you want to disable a particular message, set the option to ""
#
# The message shown when a player has started autochatting in a channel
channel-set-message: "&9Channel set: &7%channel%"
#
# The message shown when a player has stopped listening to a channel
channel-left-message: "&9Channel left: &7%channel%"
#
# The message shown when a player has started listening to a channel
now-listening-message: "&9Now listening to &7%channel%"
#
channels:
# Channels
# The options for channels are as follows:
#
# commands: [s, staffchat] - The commands that can be used to access the channel.
#
# permission: staffchannel - The permission that users must have to use/read this channel. The full permission will be easychannels.<permission>.
#
# format: "&8[&5Staff&8] &7%username%: &r%message%" - The format for messages that are shown when someone chats. Available placeholders:
#                                               - %username% - The player's username
#                                               - %displayname% - The player's displayname
#                                               - %message% - The message
#                                               - %prefix% - The player's prefix
#                                               - %suffix% - The player's suffix
#                                               - Any PAPI placeholders
#
# discord-format: "&8&o[&5&oStaff&8&o] &7%name%: &r%message%" - The format for messages that are sent to this channel from Discord.
#                                                       If this option is not specified, messages will not be sent or received from Discord.
#                                                       Available placeholders:
#                                                     - %name% - The user's displayname
#                                                     - %username% - The user's username
#                                                     - %tag% - The user's full tag
#                                                     - %message% - The message
#                                                     - Any non-player PAPI placeholders
#
# range: 200 - The distance to broadcast messages (only players within this distance will receive them). Keep in mind that if you are linking
#              this channel to Discord, you may see some unexpected behaviour. Set to a number less than 1 or remove entirely to disable.
#
# An example channel is shown below.
  - name: staff
    commands: [s, staffchat, sc]
    permission: staffchannel
    format: "&8[&5Staff&8] &7%username%: &r%message%"
    discord-format: "&8&o[&5&oStaff&8&o] &7%name%: &r%message%"
    range: -1
