name: EasyChannels
description: Chat channels, without the fuss
author: Dinty1
main: io.github.dinty1.easychannels.EasyChannels
version: ${project.version}
api-version: 1.16
load: STARTUP
depend: [Vault]
softdepend: [DiscordSRV, PlaceholderAPI]

commands:
  globalchat:
    aliases: [g]
    usage: |-
      /<command> - Return to the global channel
      /<command> <message> - Send a message to the global channel
  channels:
    aliases: [channellist, chlist, listchannels]
    permission: easychannels.listchannels
    permission-message: "§cYou do not have access to this command."
    description: Lists all channels that the player has access to.
  leavechannel:
    aliases: [leave, stoplistening, mutechannel]
    usage: /<command> <channel>
    permission: easychannels.leavechannel
    permission-message: "§cYou do not have access to this command."
    description: Stop listening to a specific channel.
  easychannels:
    usage: |-
      /<command> reloadconfig - Reloads the plugin's configuration
    description: General plugin-related commands

permissions:
  easychannels.leavechannel:
    default: true
    description: Allows the user to stop listening to a specific channel
  easychannels.listchannels:
    default: true
    description: Allows access to the /channels command.
  easychannels.adminalerts:
    default: op
    description: Allows receiving of update notifications on login
  easychannels.reloadconfig:
    default: op
    description: Allows reloading the plugin's configuration without a restart

  easychannels.admin:
    description: Contains all admin-related permissions
    default: op
    children:
      easychannels.adminalerts: true
      easychannels.reloadconfig: true

  easychannels.player:
    description: Contains all player-related permissions
    default: true
    children:
      easychannels.leavechannel: true
      easychannels.listchannels: true
