name: EasyChannels
description: Chat channels, without the fuss
author: DintyB
main: io.github.dinty1.easychannels.EasyChannels
version: ${project.version}
api-version: 1.16
load: STARTUP
depend: [Vault]
softdepend: [DiscordSRV, PlaceholderAPI]

commands:
  globalchat:
    aliases: [g]
    usage: |-
      /<command> - Return to the global channel
      /<command> <message> - Send a message to the global channel
  easychannels:
    usage: |-
      /<command> reload - Reloads the plugin's configuration.
  channels:
    aliases: [channellist, chlist, listchannels]
    permission: easychannels.listchannels
    description: Lists all channels that the player has access to.

permissions:
  easychannels.listchannels:
    default: true

